const express = require("express");
const router = express.Router();
const controller = require("../controllers/reviewController");
const authenticate  = require("../middleware/auth");
router.post("/postreview/:mal_id",authenticate,controller.createReview);
router.get('/manga/:mal_id', controller.getReviewsbyManga);
router.get('/user/:userId', controller.getReviewsByUser);
router.delete("/deletereview/:mal_id/:reviewId", authenticate, controller.deleteReview);
router.put("/updatereview/:mal_id/:reviewId",authenticate, controller.updateReview);
module.exports=router;